import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Read the API package.json at build time so the SPA's About / Settings
// version display always reflects the deployed instance — see #171.
const apiPkg = JSON.parse(
  readFileSync(fileURLToPath(new URL('../package.json', import.meta.url)), 'utf-8'),
) as { version: string };

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // autoUpdate: SW updates in the background and activates on next page
      // load. Right call for a personal care app where the user doesn't want
      // an "update available" prompt every other visit. Switch to 'prompt'
      // if we ever want explicit control.
      registerType: 'autoUpdate',
      injectRegister: 'auto',

      // The icons live under public/icons/ and are generated by the
      // build:icons prebuild step from the design-system ApothecaryStamp.
      // Keep them in includeAssets so they ship in the precache manifest.
      includeAssets: [
        'favicon.svg',
        'favicon-16.png',
        'favicon-32.png',
        'icons/bone-180.png',
        'icons/slate-180.png',
      ],

      manifest: {
        name: 'p7l',
        short_name: 'p7l',
        description: 'Plant care companion',
        start_url: '/',
        display: 'standalone',
        orientation: 'portrait',
        // Manifest only supports a single theme_color; HTML <meta> tags carry
        // the dual-mode (light/dark) variants. Bone-100 is the default light
        // surface — best default for the install prompt.
        theme_color: '#f5f3ec',
        background_color: '#f5f3ec',
        icons: [
          // Light-mode plate (bone). Browsers that honor the `media`
          // attribute will pick this when prefers-color-scheme: light.
          {
            src: 'icons/bone-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any maskable',
            // @ts-expect-error — `media` is valid per the manifest spec but
            // not yet in vite-plugin-pwa's TS types.
            media: '(prefers-color-scheme: light)',
          },
          {
            src: 'icons/bone-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
            // @ts-expect-error — see above.
            media: '(prefers-color-scheme: light)',
          },
          // Dark-mode plate (slate).
          {
            src: 'icons/slate-192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'any maskable',
            // @ts-expect-error — see above.
            media: '(prefers-color-scheme: dark)',
          },
          {
            src: 'icons/slate-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'any maskable',
            // @ts-expect-error — see above.
            media: '(prefers-color-scheme: dark)',
          },
          // Browsers that don't read `media` fall back to the first matching
          // size — bone is listed first, so it wins as the "no preference" default.
        ],
      },

      workbox: {
        // Precache the app shell on first install.
        globPatterns: ['**/*.{js,css,html,svg,png,webmanifest}'],

        // The dev tunnel sometimes serves /api/* through a Cloudflare hop;
        // exclude it from precache so we never serve stale data.
        navigateFallbackDenylist: [/^\/api/],

        runtimeCaching: [
          // Read endpoints — stale-while-revalidate so the UI loads instantly
          // from cache and updates in the background.
          {
            urlPattern: ({ url, request }) =>
              request.method === 'GET' &&
              /\/api\/(plants(\?.*)?|plants\/\d+|schedule\/week|screen)(\?|$)/.test(url.pathname + url.search),
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'p7l-api-get',
              expiration: {
                maxEntries: 64,
                maxAgeSeconds: 60 * 60 * 24, // 24 hours
              },
              cacheableResponse: { statuses: [0, 200] },
            },
          },

          // Mutations — Background Sync queue. The Queue persists failed
          // POSTs in IndexedDB. Browsers with the Background Sync API
          // (Android Chrome, iOS Safari 17.4+) replay automatically on
          // reconnect. Older iOS Safari keeps the queue in IndexedDB and
          // the plugin retries on the next SW activation, which fires on
          // every fresh visit — so worst case is a one-revisit replay
          // delay, not data loss.
          {
            urlPattern:
              /\/api\/plants(\/\d+)?\/(water|undo-water|water-all|undo-batch)$/,
            handler: 'NetworkOnly',
            method: 'POST',
            options: {
              backgroundSync: {
                name: 'p7l-water-queue',
                options: { maxRetentionTime: 24 * 60 }, // minutes — 24h
              },
            },
          },
          {
            urlPattern: /\/api\/plants\/\d+\/calibration$/,
            handler: 'NetworkOnly',
            method: 'POST',
            options: {
              backgroundSync: {
                name: 'p7l-calibration-queue',
                options: { maxRetentionTime: 24 * 60 },
              },
            },
          },
          {
            // Archive flow: PUT /api/plants/:id with archive flag. Same queue
            // semantics — these are user-initiated mutations that must replay.
            urlPattern: /\/api\/plants\/\d+$/,
            handler: 'NetworkOnly',
            method: 'PUT',
            options: {
              backgroundSync: {
                name: 'p7l-edit-queue',
                options: { maxRetentionTime: 24 * 60 },
              },
            },
          },
        ],
      },

      devOptions: {
        // SW disabled in dev by default — turning it on with `enabled: true`
        // is occasionally useful for local debugging. Keep off for routine
        // dev to avoid stale-cache surprises.
        enabled: false,
      },
    }),
  ],
  define: {
    __APP_VERSION__: JSON.stringify(apiPkg.version),
  },
  server: {
    port: 5173,
    proxy: {
      '/api': 'http://localhost:3900',
    },
  },
  build: {
    outDir: '../dist/client',
    emptyOutDir: true,
  },
});
